# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/fifo_shift_window/fifo_shift_window.xci
# IP: The module: 'fifo_shift_window' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/fifo_shift_window/fifo_shift_window.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_shift_window'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/fifo_shift_window/fifo_shift_window_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_shift_window'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/fifo_shift_window/fifo_shift_window_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_shift_window'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/fifo_shift_window/fifo_shift_window.xci
# IP: The module: 'fifo_shift_window' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/fifo_shift_window/fifo_shift_window.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_shift_window'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/fifo_shift_window/fifo_shift_window_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_shift_window'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/fifo_shift_window/fifo_shift_window_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_shift_window'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
