# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/floating_point_compare/floating_point_compare.xci
# IP: The module: 'floating_point_compare' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/floating_point_compare/floating_point_compare_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_compare'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/floating_point_compare/floating_point_compare.xci
# IP: The module: 'floating_point_compare' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/floating_point_compare/floating_point_compare_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_compare'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
