# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param general.maxThreads 8
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/postureRec/posture_recognition/posture_recognition.cache/wt [current_project]
set_property parent.project_path D:/postureRec/posture_recognition/posture_recognition.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu102:part0:3.2 [current_project]
set_property ip_output_repo d:/postureRec/posture_recognition/posture_recognition.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/post_image_ram/PostImage_ram_init_data.coe
read_verilog D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/network_parameters.vh
set_property is_global_include true [get_files D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/network_parameters.vh]
read_verilog -library xil_defaultlib -sv D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/cal_channel_choose.sv
read_verilog -library xil_defaultlib {
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/AXI_4KBboundary.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/CalImageChannel_replication.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/activation.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/addTree.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/addr_mux.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/axi_interface_control.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/axi_read_image_cnt.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/axi_read_write_master.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/bandWidth_count.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/batch_norm.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/buffer_control.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/cal_image.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/conv.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/counter_addr.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/data_from_window.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/deal_PostImage.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/err_detect.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/head_bufer_control.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/image_ram_multi_addr.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/image_read_buffer_control.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/image_shift_rc_noaddzero_cnt.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/image_write_buffer_control.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/information_read_write.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/interrupt.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/iterate_head.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/kernel_buffer_control.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/leaky_activation.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/linear_activation.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/load_data.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/load_head.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/load_image.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/load_kernel.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/max_pooling.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/mul_results_adder.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/multi_div.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/multi_rd_addr.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/multiplier_3x.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/mux_3to1.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/mux_head_image_kernel.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/mux_ramtofifo_data.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/postImage_channel_choose.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/post_to_ram_virtual_path.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/ram_to_cal_virtual_path.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/ram_to_post_virtual_path.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/reset.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/row_col_ptr_gen_for_2unite.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/shift_control.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/shift_window.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/stayInstep.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/sub_com.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/sumChannels.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/summation.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/update.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/user_maxpooling_fifo.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/user_update_fifo.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/wfifo_location_cal.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/wr_rd_finish_cnt_threshhold.v
  D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/new/pl_top.v
}
read_ip -quiet D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/combine2data_fifo/combine2data_fifo.xci
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/combine2data_fifo/combine2data_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/combine2data_fifo/combine2data_fifo_ooc.xdc]

read_ip -quiet D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/fifo_shift_window/fifo_shift_window.xci
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/fifo_shift_window/fifo_shift_window.xdc]
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/fifo_shift_window/fifo_shift_window_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/fifo_shift_window/fifo_shift_window_ooc.xdc]

read_ip -quiet D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/float_add_IP_use_DSP_multilatency/float_add_IP_use_DSP_multilatency.xci
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/float_add_IP_use_DSP_multilatency/float_add_IP_use_DSP_multilatency_ooc.xdc]

read_ip -quiet D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/float_multiply/float_multiply.xci
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/float_multiply/float_multiply_ooc.xdc]

read_ip -quiet D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/floating_point_compare/floating_point_compare.xci
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/floating_point_compare/floating_point_compare_ooc.xdc]

read_ip -quiet D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/head_fifo/head_fifo.xci
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/head_fifo/head_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/head_fifo/head_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/head_fifo/head_fifo_ooc.xdc]

read_ip -quiet D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/head_for_interate_dram/head_for_interate_dram.xci
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/head_for_interate_dram/head_for_interate_dram_ooc.xdc]

read_ip -quiet D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/image_prerd_toaxi_fifo/image_prerd_toaxi_fifo.xci
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/image_prerd_toaxi_fifo/image_prerd_toaxi_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/image_prerd_toaxi_fifo/image_prerd_toaxi_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/image_prerd_toaxi_fifo/image_prerd_toaxi_fifo_ooc.xdc]

read_ip -quiet D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/image_ram/image_ram.xci
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/image_ram/image_ram_ooc.xdc]

read_ip -quiet D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/image_ram_rd_addr_add/image_ram_rd_addr_add.xci
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/image_ram_rd_addr_add/image_ram_rd_addr_add_ooc.xdc]

read_ip -quiet D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/kernel_fifo/kernel_fifo.xci
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/kernel_fifo/kernel_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/kernel_fifo/kernel_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/kernel_fifo/kernel_fifo_ooc.xdc]

read_ip -quiet D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/PLL/PLL.xci
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/PLL/PLL_board.xdc]
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/PLL/PLL.xdc]
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/PLL/PLL_ooc.xdc]

read_ip -quiet D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/post_image_ram/post_image_ram.xci
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/post_image_ram/post_image_ram_ooc.xdc]

read_ip -quiet D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/stayInstep_fifo/stayInstep_fifo.xci
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/stayInstep_fifo/stayInstep_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/stayInstep_fifo/stayInstep_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/stayInstep_fifo/stayInstep_fifo_ooc.xdc]

read_ip -quiet D:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/sub_unit/sub_unit.xci
set_property used_in_implementation false [get_files -all d:/postureRec/posture_recognition/posture_recognition.srcs/sources_1/ip/sub_unit/sub_unit_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/postureRec/posture_recognition/posture_recognition.srcs/constrs_1/new/pin.xdc
set_property used_in_implementation false [get_files D:/postureRec/posture_recognition/posture_recognition.srcs/constrs_1/new/pin.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top pl_top -part xczu9eg-ffvb1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pl_top.dcp
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
